const CONFIG = {
  businessName: "Alamo Solutions",
  niche: "Roofing",
  tagline: "Trusted Roofing Services in San Antonio",
  phone: "",
  phoneRaw: "",
  email: "",
  city: "San Antonio",
  state: "Texas",
  stateShort: "TX",
  address: "San Antonio, TX",
  licenseNumber: "",
  colors: { primary: "#0F766E", secondary: "#1C2333" },
  social: { facebook: "", instagram: "", youtube: "", yelp: "", nextdoor: "" },
  googleReviewsUrl: "",
  rating: "",
  reviewCount: 0,
  yearsExperience: 0,
  projectsCompleted: "0+",
  satisfactionRate: "98%",
  webhookUrl: "",
  metaPixelId: "",
  maps: { mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d109867.75389650742!2d-98.61439266399435!3d29.42396349942091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865c58af04c0c1b5%3A0x8562c353b9c37279!2sSan%20Antonio%2C%20TX!5e0!3m2!1sen!2sus!4v1701550993188!5m2!1sen!2sus", mapSearchQuery: "Alamo Solutions Roofing San Antonio TX", mapHeight: 420 },
  hero: {
    eyebrow: "Local Home Service Professionals",
    headline: "Protect Your San Antonio Home with Expert Roofing",
    subheadline: "Reliable, durable, and beautiful roofing solutions tailored for the Texas climate.",
    ctaPrimary: "Get a Free Estimate",
    ctaSecondary: "Explore Services",
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&q=80&auto=format&fit=crop",
  },
  services: [
    {
      slug: "roof-repair",
      name: "Roof Repair",
      desc: "Expert repair services to fix leaks, storm damage, and wear, extending your roof's lifespan.",
      longDesc: "From minor leaks to significant storm damage, our skilled technicians provide comprehensive roof repair services. We diagnose the issue accurately, use high-quality materials, and ensure repairs blend seamlessly with your existing roof, preventing further damage and preserving your home's integrity.",
      benefits: ["Stop leaks quickly", "Prevent further damage", "Extend roof lifespan", "Cost-effective solutions"],
      faqs: [
        { q: "How do I know if my roof needs repair?", a: "Signs include missing shingles, water stains on ceilings, granules in gutters, or visible damage after a storm. We offer free inspections to assess your roof's condition." },
        { q: "How long does a typical roof repair take?", a: "Most repairs can be completed within a day, depending on the extent of the damage. We work efficiently to minimize disruption to your home." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "roof-replacement",
      name: "Roof Replacement",
      desc: "Complete roof replacement services for an enhanced look and long-term protection.",
      longDesc: "When repairs are no longer sufficient, our roof replacement service provides a fresh start. We guide you through material selection—from asphalt shingles to metal and tile—and execute a professional installation that enhances your home's curb appeal, energy efficiency, and provides superior protection for decades.",
      benefits: ["Increased home value", "Superior weather protection", "Improved energy efficiency", "Wide range of material options"],
      faqs: [
        { q: "How long does a roof replacement take?", a: "Most residential roof replacements are completed within 2-5 days, depending on the roof's size, complexity, and weather conditions." },
        { q: "What types of roofing materials do you offer?", a: "We offer a variety of materials including asphalt shingles, metal roofing, tile roofing, and flat roofing solutions, tailored to your aesthetic and budget." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "new-roof-installation",
      name: "New Roof Installation",
      desc: "Professional installation of new roofs for new constructions and additions, built to last.",
      longDesc: "For new constructions or home additions, our new roof installation service ensures a high-quality, durable roof from the ground up. We work closely with builders and homeowners to select the best materials and design that complement the structure, providing expert craftsmanship and adherence to all building codes.",
      benefits: ["Custom design and material selection", "Long-lasting protection", "Expert craftsmanship", "Guaranteed quality"],
      faqs: [
        { q: "Can I choose my roofing material for a new build?", a: "Absolutely! We'll help you explore options like asphalt, metal, or tile to find the perfect fit for your home's style and your budget." },
        { q: "What is the typical warranty for a new roof installation?", a: "We offer comprehensive warranties on both materials and labor, ensuring your peace of mind for years to come. Specific terms depend on the chosen materials." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "roof-inspections",
      name: "Roof Inspections",
      desc: "Thorough roof inspections to identify potential issues and ensure long-term health.",
      longDesc: "Our detailed roof inspections help you catch small issues before they become major problems. We assess your roof's condition, identify wear and tear, storm damage, or potential vulnerabilities, providing you with a comprehensive report and honest recommendations for maintenance or repair.",
      benefits: ["Early problem detection", "Prevent costly repairs", "Extend roof lifespan", "Peace of mind"],
      faqs: [
        { q: "How often should I have my roof inspected?", a: "We recommend annual inspections, especially after severe weather, or if your roof is over 10 years old, to catch issues early." },
        { q: "What does a roof inspection involve?", a: "Our inspectors examine shingles, flashing, gutters, vents, and the overall structure for damage, wear, and potential leaks, both externally and from the attic if accessible." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "emergency-roofing",
      name: "Emergency Roofing Services",
      desc: "Rapid response for urgent roof damage caused by storms, fallen trees, or unexpected leaks.",
      longDesc: "When disaster strikes, our emergency roofing team is ready to provide immediate assistance. We offer temporary tarping and urgent repairs to prevent further water intrusion and secure your property, minimizing damage until permanent repairs can be scheduled.",
      benefits: ["24/7 rapid response", "Prevent further damage", "Secure your property", "Expert crisis management"],
      faqs: [
        { q: "What constitutes a roofing emergency?", a: "Severe leaks, major storm damage, fallen trees, or any situation where your home is immediately vulnerable to water intrusion or structural compromise." },
        { q: "How quickly can you respond to an emergency?", a: "We aim to respond to emergency calls as quickly as possible, often within hours, to provide immediate temporary solutions and assess the damage." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "commercial-roofing",
      name: "Commercial Roofing",
      desc: "Specialized roofing solutions for businesses and commercial properties in San Antonio.",
      longDesc: "We provide comprehensive commercial roofing services, including installation, repair, and maintenance for various business properties. Our expertise covers different commercial roofing systems, ensuring durability, energy efficiency, and minimal disruption to your operations.",
      benefits: ["Durable commercial solutions", "Minimal business disruption", "Energy-efficient options", "Long-term asset protection"],
      faqs: [
        { q: "What types of commercial roofing systems do you work with?", a: "We handle various systems including TPO, EPDM, PVC, modified bitumen, and metal roofing for commercial properties." },
        { q: "Do you offer maintenance plans for commercial roofs?", a: "Yes, we provide customized maintenance plans to prolong the life of your commercial roof and prevent costly issues." },
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
  ],
  serviceAreas: [
    { slug: "san-antonio", name: "San Antonio", county: "" },
    { slug: "boerne", name: "Boerne", county: "" },
    { slug: "helotes", name: "Helotes", county: "" },
    { slug: "leon-valley", name: "Leon Valley", county: "" },
    { slug: "shavano-park", name: "Shavano Park", county: "" },
    { slug: "castle-hills", name: "Castle Hills", county: "" },
    { slug: "alamo-heights", name: "Alamo Heights", county: "" },
    { slug: "fair-oaks-ranch", name: "Fair Oaks Ranch", county: "" },
    { slug: "stone-oak", name: "Stone Oak", county: "" },
    { slug: "timberwood-park", name: "Timberwood Park", county: "" },
    { slug: "bulverde", name: "Bulverde", county: "" },
    { slug: "schertz", name: "Schertz", county: "" },
    { slug: "cibolo", name: "Cibolo", county: "" },
    { slug: "selma", name: "Selma", county: "" },
    { slug: "universal-city", name: "Universal City", county: "" },
    { slug: "live-oak", name: "Live Oak", county: "" },
    { slug: "converse", name: "Converse", county: "" },
    { slug: "windcrest", name: "Windcrest", county: "" },
    { slug: "kirby", name: "Kirby", county: "" },
    { slug: "new-braunfels", name: "New Braunfels", county: "" }
  ],
  testimonials: [
    { name: "Maria", text: "Alamo Solutions did an amazing job replacing our roof in San Antonio. The team was professional, efficient, and the new roof looks fantastic. Highly recommend their services!", rating: 5 },
    { name: "David", text: "We had a leak after a storm, and Alamo Solutions responded quickly. Their repair work was thorough and precise. Our roof is secure again, thanks to their prompt service in San Antonio.", rating: 5 },
    { name: "Sarah", text: "I needed a full roof replacement, and Alamo Solutions walked me through every step. They helped me choose the best materials for my home in San Antonio and completed the project on time and within budget. Excellent work!", rating: 5 },
    { name: "James", text: "Professional and honest! Alamo Solutions inspected my roof in San Antonio and gave me a clear report. They fixed the issues without trying to upsell me. A truly trustworthy roofing company.", rating: 5 },
  ],
  processSteps: [
    { title: "Tell Us About Your Project", desc: "Share your goals and schedule a convenient consultation." },
    { title: "Receive a Clear Plan", desc: "We assess the work and provide a straightforward recommendation." },
    { title: "Professional Service", desc: "Our team completes the job with care and clear communication." },
    { title: "Final Walkthrough", desc: "We make sure the completed work meets your expectations." },
  ],
  faqs: [
    { q: "How often should I have my roof inspected in San Antonio?", a: "Given San Antonio's climate with hot summers and occasional severe storms, we recommend a professional roof inspection at least once a year, and definitely after any major weather event." },
    { q: "What are the signs that I need a new roof?", a: "Common signs include missing or cracked shingles, granules in your gutters, a sagging roof deck, water stains on your ceiling, or if your roof is over 20-25 years old." },
    { q: "How long does a roof replacement typically take?", a: "The duration of a roof replacement depends on the size and complexity of your roof, as well as weather conditions. Most residential projects in San Antonio are completed within 2 to 5 days." },
    { q: "Do you offer financing options for roofing projects?", a: "Yes, we understand that a new roof is a significant investment. We offer flexible financing options to help make your roofing project affordable. Contact us to learn more." },
    { q: "Are your roofing contractors licensed and insured in Texas?", a: "Absolutely. All our roofing professionals are fully licensed and insured, providing you with peace of mind and ensuring your project is handled by qualified experts." },
    { q: "What types of roofing materials do you work with?", a: "We specialize in a variety of roofing materials including asphalt shingles, metal roofing, tile roofing, and flat roofing systems, offering solutions to fit every home style and budget in San Antonio." },
    { q: "How do I get an estimate for my roofing project?", a: "Getting a free estimate is easy! Simply contact us by phone or fill out our online form, and we'll schedule a convenient time to assess your roof and provide a detailed quote." },
  ],
  portfolioProjects: [],
  legal: { privacyPolicyDate: "May 1, 2025", termsDate: "May 1, 2025" },
};